name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: echo "${ message }" | npx commitlint
      env:
          message: ${{ github.event.head_commit.message }}
